feat: Add Python 3.9 support
fyntex/fd-django-accounts pull request #190
Opened 2022-11-08 23:16 UTC by ycouce-cdd

- Add version to Setuptools script.
- Add Tox environment.
- Add version to CI configuration.
- Update Docker Compose configuration.
- Update Make task for running tests: `docker-compose-run-test`.

More info: https://docs.python.org/3.9/whatsnew/3.9.html
Ref: https://cordada.aha.io/features/COMPCLDATA-162

2022-11-10 16:14 UTC, jtrobles-cdd requested changes
- [ ] Shouldn't the commit type be `chore` instead of `feat`?
- [ ] In the commit message, can you add an empty line before `Ref:` so that Git is able to recognize `Ref:` as a trailer?

2022-11-10 20:10 UTC, ycouce-cdd commented
> * [ ]  Shouldn't the commit type be `chore` instead of `feat`?

Your call, I used as reference a PR in this repository (https://github.com/fyntex/fd-django-accounts/pull/13), which classified as `feature` these changes, according to the branch name.
If we now use new guidelines, I can change it, but the branch name would still be prefixed with `feature`.

2022-11-11 16:26 UTC, jtrobles-cdd commented
> > * [ ]   Shouldn't the commit type be `chore` instead of `feat`?
> 
> Your call, I used as reference a PR in this repository (#13), which classified as `feature` these changes, according to the branch name. If we now use new guidelines, I can change it, but the branch name would still be prefixed with `feature`.

Good point. I guess that adding support for a new Python version could be considered a feature.

2022-11-11 16:26 UTC, jtrobles-cdd approved these changes

2022-11-11 18:39 UTC, merged