chore: Add support for Python 3.10
fyntex/fd-django-accounts pull request #199
Opened 2022-12-29 17:45 UTC by svillegas-cdd

* Add Python 3.10 to Setuptools script.
* Add Tox environment for Python 3.10.
* Add Python 3.10 to CircleCI configuration.
* Add Python 3.10 .black target-version
* Update `docker-compose.yml` file

More information: https://docs.python.org/3.10/whatsnew/3.10.html

Ref: https://cordada.aha.io/features/COMPCLDATA-163

2022-12-29 19:36 UTC, ycouce-cdd requested changes

2022-12-29 19:36 UTC, ycouce-cdd commented on docker-compose.test.yml
> +version: "3.10"
This is a property of the compose file for backward compatibility.

```suggestion
version: "3.9"
```

2022-12-29 19:36 UTC, ycouce-cdd commented on docker-compose.yml
> +version: "3.10"
```suggestion
version: "3.9"
```

2022-12-29 19:36 UTC, ycouce-cdd commented on tox.ini
> +    py310,
Please, add the environment `py39` to the list of environments (we missed this change in #190)

```suggestion
    py39,
    py310,
```

2022-12-31 16:30 UTC, ycouce-cdd approved these changes

2023-01-04 15:11 UTC, fpinto-cdd approved these changes

2023-01-04 15:27 UTC, merged