Add Codecov to CI workflow
fyntex/fd-django-accounts pull request #234
Opened 2023-05-23 19:34 UTC by svillegas-cdd

> Codecov is the all-in-one code coverage reporting solution for any
> test suite — giving developers actionable insights to deploy reliable
> code with confidence.

- Codecov web site: https://about.codecov.io/
- Documentation: https://docs.codecov.com/

Ref: https://cordada.aha.io/requirements/TECHINFRA-194-10
Ref: https://cordada.aha.io/features/TECHINFRA-194

2023-05-23 20:32 UTC, jtrobles-cdd commented
Codecov URL for this repository: https://app.codecov.io/gh/fyntex/fd-django-accounts

2023-05-23 20:35 UTC, jtrobles-cdd requested changes
Add badge to readme.

```rst
.. image:: https://codecov.io/gh/fyntex/fd-django-accounts/branch/develop/graph/badge.svg?token=yvUoIRtsm5 
 :target: https://codecov.io/gh/fyntex/fd-django-accounts
```

2023-05-23 20:55 UTC, jtrobles-cdd requested changes

2023-05-23 20:55 UTC, jtrobles-cdd commented on Makefile
> +.PHONY: lint lint-fix test test-all test-coverage
There is no `lint-fix` Make target.

2023-05-24 21:07 UTC, fpinto-cdd approved these changes

2023-06-05 13:37 UTC, merged